### PR TITLE
Add Colemak-DH support

### PR DESCRIPTION
**Pull request by minerscale**
Colemak DH is the most common mod of colemak and either support should be added like this or the ability to upload custom keymaps as json files should be added (happy to try to implement this feature if it's wanted)

### CODE REVIEW

**Comment by vsicurella** [comment]
This would probably be fine, but #124 seeks to remove the dependency on numerous key maps altogether! Once that's finished, we'll automatically support any layout :)

**Comment by minerscale** [comment]
Actually, I use a momoka_ergo keyboard colemak-dhm programmed directly into the keyboard using qmk, so scancodes are as good as useless for me, I actually need to be able to change the bindings for things. It's a bit of an accessibility nightmare. I've defined a qwerty compatibility layer but it's far from convenient (typing becomes very, very hard). So whilst using scancodes much improves the accessibility issue it doesn't entirely fix it.

**Comment by SeanArchibald** [comment]
Thanks for commenting on #124. When moving to scancodes we'll have to remember that some users need a special keymap to fall back to. Not sure exactly how that is going to work but for now I will merge your new keymap into the develop branch and include it as a keymap option.

**Comment by SeanArchibald** [comment]
I've added a menu option so that you can select your new layout. You'll need to pull the changes on the develop branch. Is that working ok for you @minerscale?

**Comment by minerscale** [comment]
> I've added a menu option so that you can select your new layout. You'll need to pull the changes on the develop branch. Is that working ok for you @minerscale?

Just tested it, it's working flawlessly. I got the layout right which is good news. Thank you very much!

**Pull request merged**
